UNAUTHORIZED = "UNAUTHORIZED"

PAYMENT_ERROR = "PAYMENT_ERROR"
INTERNAL_ERROR = "INTERNAL_ERROR"
VALIDATION_ERROR = "VALIDATION_ERROR"
USER_ERROR = "USER_ERROR"

TRANSATION_ERROR = "TRANSATION_ERROR"
TRANSACTION_NOT_FOUND = "TRANSACTION_NOT_FOUND"
INSUFFICIENT_BALANCE = "INSUFFICIENT_BALANCE"
INVALID_AMOUNT = "INVALID_AMOUNT"